### ISSUE TITLE
Fix compilation

### ISSUE THREAD

**Issue by drasko** [ultravioletrs/cocos-ai#1]
This repo was created by merging https://github.com/ultravioletrs/manager and and https://github.com/ultravioletrs/agent into monorepo.

Fix compilation errors by observing how Manager and Agent work individually and following the best practices used in the Magistrala project.
